excel_parsing_task:
  description: >
    Coordinate the parsing and normalization of uploaded Excel files. Handle unpredictable 
    Excel formats, extract financial data, and standardize it for analysis. Validate data 
    integrity and prepare it for risk assessment.
  expected_output: >
    A structured JSON object containing normalized financial data with validated columns, 
    amounts, dates, and metadata. Include parsing logs and data quality indicators.
  agent: manager_agent

risk_assessment_task:
  description: >
    Evaluate the extracted financial data against user-defined constraints including minimum 
    balance requirements, transaction limits, and special conditions. Generate a comprehensive 
    risk assessment report considering financial regulations and compliance requirements.
    Input: {financial_data} and {user_constraints}
  expected_output: >
    A detailed risk assessment report in JSON format containing risk score, compliance status, 
    identified risks, recommendations, and validation of user constraints. Include specific 
    flagged transactions if any.
  agent: risk_assessor_agent

payment_proposal_task:
  description: >
    Generate a structured payment proposal based on validated financial data and risk assessment 
    results. Format the proposal for human review with clear transaction details, amounts, 
    recipients, and compliance information.
    Input: {validated_data} and {risk_report}
  expected_output: >
    A formatted payment proposal in JSON format ready for HITL review, containing transaction 
    details, total amounts, risk summary, and all required metadata for execution.
  agent: payment_specialist_agent

investment_allocation_task:
  description: >
    Create an investment allocation plan for remaining funds after payment execution. Analyze 
    options including fiat time deposits, crypto/DeFi products, and liquidity solutions. 
    Generate structured plan with allocation percentages, expected yields, durations, and risk levels.
    Input: {remaining_balance} and {investment_preferences}
  expected_output: >
    A comprehensive investment plan in JSON format containing allocation by type (fiat/crypto/liquidity), 
    expected yield/interest rates, duration or lock-up periods, risk levels, and detailed 
    execution instructions.
  agent: investment_agent

workflow_orchestration_task:
  description: >
    Orchestrate the entire treasury workflow ensuring proper task sequencing, HITL checkpoint 
    integration, error handling, and compliance monitoring. Coordinate between all agents and 
    manage workflow state transitions.
    Input: {workflow_inputs} and {hitl_responses}
  expected_output: >
    A complete workflow execution report in JSON format containing task results, HITL checkpoint 
    statuses, execution confirmations, audit trail, and final outcome summary.
  agent: manager_agent
