workflow_coordination:
  description: >
    Coordinate the entire treasury workflow, ensuring all tasks are completed in the correct sequence.
    Monitor compliance with constraints and enforce HITL checkpoints at critical stages.
    Delegate tasks to specialized agents and collect their outputs for decision making.
  expected_output: >
    A comprehensive workflow execution report including all completed tasks, decisions made,
    HITL checkpoint results, and final status of the treasury operation.
  agent: manager

risk_assessment:
  description: >
    Analyze the financial data extracted from the Excel file and evaluate risks based on:
    - Data integrity and completeness
    - User-defined constraints (minimum balance: {minimum_balance}, transaction limits: {transaction_limits})
    - Payment amounts and recipients
    - Overall financial exposure
    Generate a detailed risk assessment report with risk scores and recommendations.
  expected_output: >
    A structured risk assessment report containing:
    - Overall risk level (low/medium/high)
    - Risk score (0-100)
    - Specific risk flags identified
    - Compliance status with user constraints
    - Recommendations for risk mitigation
  agent: risk_assessor

payment_proposal_generation:
  description: >
    Create a structured payment proposal based on the validated financial data and risk assessment.
    Format the proposal for human review with clear payment details, amounts, and recipients.
    Ensure all payments comply with organizational policies and constraints.
  expected_output: >
    A formatted payment proposal containing:
    - Unique proposal ID
    - List of all payments with recipients, amounts, and references
    - Total payment amount and remaining balance
    - Risk assessment summary
    - Constraints validation results
    - HITL approval requirements
  agent: payment_specialist

payment_execution:
  description: >
    Execute the approved payment proposal after receiving HITL approval.
    Process each payment transaction and track execution status.
    Generate execution report with transaction confirmations and updated balances.
  expected_output: >
    Payment execution report containing:
    - Execution ID and status
    - Transaction details for each payment
    - Success/failure status for each transaction
    - Processing fees and net amounts
    - Updated balance information
  agent: payment_specialist

investment_planning:
  description: >
    Analyze the remaining balance after payment execution and create an optimized investment plan.
    Consider risk tolerance: {risk_tolerance} and investment preferences.
    Allocate funds across liquidity products, stablecoins, and other short-term investments.
    Generate a detailed investment plan with expected returns and risk analysis.
  expected_output: >
    A comprehensive investment plan containing:
    - Unique plan ID
    - Allocation across different investment types
    - Expected yields and returns
    - Risk profile and diversification analysis
    - Liquidity analysis
    - Recommendations for optimization
    - HITL approval requirements
  agent: investment_agent

investment_execution:
  description: >
    Execute the approved investment plan after receiving HITL approval.
    Allocate funds to the specified investment products and track execution status.
    Generate execution report with investment confirmations and expected maturity dates.
  expected_output: >
    Investment execution report containing:
    - Execution status for each allocation
    - Investment confirmations and reference numbers
    - Expected maturity dates and yields
    - Total invested amount
    - Execution timestamps
  agent: investment_agent
