---
# Treasury Agent Tools Configuration
# All configurable parameters for treasury management tools

payment_executor:
  processing_fee_rate: 0.001  # 0.1% processing fee for payments
  default_currency: "USDT"    # Default currency for payments
  simulation_mode: true       # Always run in simulation mode for safety


# Environment-specific overrides (can be set via env vars)
environment:
  processing_fee_rate: ${TREASURY_PROCESSING_FEE_RATE:0.001}
  default_currency: ${TREASURY_CURRENCY:USDT}
